<a href="https://colab.research.google.com/github/RajeshRanaGiet/IML-Lab/blob/main/Experiment-2/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a1 = np.array([1,2,3,4,5,6])
print(a1)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
add=arr+5
print(add)
mul=arr*5
print(mul)
exp=arr**2
print(exp)

6
[ 4 10 18]
[ 2.71828183  7.3890561  20.08553692]


In [ ]:
a1 = np.array([1,2,3,4,5,6])
print("First element is ", a1[0])
print("Last element is ", a1[-1])
print("From 2 to 4 element is ", a1[2:5])

First element is  1
Last element is  6
From 2 to 4 element is  [3 4 5]


In [ ]:
import numpy as np

a1 = np.array([[1, 2, 3],[4, 5, 6]])

a2 = np.array([[1, 2],[3, 4],[5, 6]])

a3 = np.zeros((2, 2))

for i in range(2):
    for j in range(2):
        for k in range(3):
            a3[i][j] += a1[i][k] * a2[k][j]

print(a3)


[[22. 28.]
 [49. 64.]]


In [ ]:
a1 = [1,2,3,4,5,6]
print('Maximum is', np.max(a1))
print("Mininmum is", np.min(a1))
print("Average maximum is", np.argmax(a1))
print("Average minimum is", np.argmin(a1))

Maximum is  6


In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print(np.concatenate((a1, a2)))
print(np.stack((a1, a2)))
print(np.vstack((a1, a2)))


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print("Element wise equal", a1 == a2)
print("Element wise greater", a1 > a2)
print("Element wise less", a1 < a2)

Element wise equal [False False False]
Element wise greater [False False False]
Element wise less [ True  True  True]
